# TypeProf 0.21.7

# Classes
module McRecord
  class ContentNotFound < StandardError
  end

  class Base
    extend ActiveSupport::Concern
    @attributes: untyped
    @@end_point: untyped

    def initialize: (untyped attributes) -> void
    def self.config: (service_domain: untyped, api_key: untyped, end_point: untyped) -> untyped
    def self.all: -> Array[Base]
    def self.find: (untyped id) -> Base
    def self.where: (untyped arg) -> Array[Base]
    def self.where_not: (untyped arg) -> Array[Base]
    def self.define_method_attribute_if_needed: (untyped attr_name) -> nil
    def self.build_filter_params: (untyped arg) -> untyped
    def self.build_not_filter_params: (untyped arg) -> untyped
    def self.open_structs_to_instances: (Array[untyped] contents) -> Array[Base]
    def self.fetch_contents: (?nil param) -> Array[untyped]

    private
    def read_attribute: (untyped attr_name) -> untyped
    def write_attribute: (untyped attr_name, untyped value) -> untyped
  end
end
